repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.1
    hooks:
      - id: clang-format
        files: '\.(glsl|frag|vert|cc|cpp|hpp|h|c|cxx|hxx|rchit|rgen|rmiss|comp|proto)$'
        types_or: ['text']


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
